# NOTE: update this with your service name
service: webpack-lifecycle-probs

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - example1
  - serverless-webpack
  - serverless-offline

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
